FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# goMake Flight API 1.0
The goMake Flight API provides flight related information and realtime telemetry data for goMake high altitude balloon and other project launches. 

The goMake Flight API uses [JWT](https://jwt.io/) to provide authorization to a client with a valid *API Key*. The API is currently in *alpha* mode and API Keys must be requested via email to team@gomake.io.

## Flight Roster [/flight]
### Get a list of flights [GET]
+ Request (application/json)
    + Headers
        Authentication: (JWT Token)
    + Body
    + Schema
+ Response 200 (application/json)
    + Body
        {
            "content": [
                { 
                    "id": 1,
                    "callsign": "GOMAKE",
                    "flightNumber": 1
                },
                {
                    "id": 2,
                    "callsign": "HOLYOKE",
                    "flightNumber": 2
                }
            ],
            "_links": {
                "self": { "href": "" }
            }
        }
    + Schema
+ Response 401 (application/json)
Unauthorized API Key
## Flights [/flight/{callsign}-{flightNumber}]
### Get flight information [GET]
Provides details surrounding a specific flight. A flight in the goMake API is designated by a callsign (i.e. GOMAKE) and a flight number (i.e. '1'). They will often be depicted together, separated by a hyphen (i.e. 'GOMAKE-1').
+ Parameters
    + callsign: gomake (required) - Unique identifier for organization or group doing the launches
    + flightNumber: 1 (required) - Unique identifier for flight under a particular callsign
+ Headers
    Authentication: (JWT Token)
+ Request (application/json)
    + Headers
    + Body
    + Schema
+ Response 200 (application/json)
    + Body
        {
              "content": [
                 {
                   "callsign": "GOMAKE",
                   "flightNumber": 1,
                   "createdAt": "mm-dd-YYYY",
                   "launchStartDateTime": "mm-dd-YYYY",
                   "launchLocation": "-41.123, 107.8543",
                   "launchAltitude": 70,
                   "registeredTrackers": [1,13,26]
                 }    
             ],
             "_links": {
                 "self": { "href": "/flight/gomake-1" },
                 "telemetry": { "href": "/flight/gomake-1/telemetry" },
                 "tracker": { "href": "/flight/gomake-1/tracker" },
                 "history": { "href": "/flight/gomake-1/history" }
             }
        }
    + Schema
        {}
+ Response 401 (application/json)
Unauthorized API Key
### Add a flight [POST]
Adds a flight to the flight roster. 
+ Headers
    Authentication: (JWT Token)
+ Request (application/json)
    + Body
        {
            "callsign": "GOMAKE",
            "flightNumber": 1,
            "launchStartDateTime": "mm-dd-YYYY",
            "launchLocation": "-41.123, 107.8543",
            "launchAltitude": 70
        }
    + Schema
+ Response 200 (application/json)
Successful request.
+ Response 400 (application/json)
Failed to include needed flight information or headers.
### Update flight information [PUT]
+ Headers
    Authentication: (JWT Token)
+ Request (application/json)
    + Body
        {
            "id": 1,
            "callsign": "GOMAKE",
            "flightNumber": 1,
            "launchStartDateTime": "mm-dd-YYYY",
            "launchLocation": "-41.123, 107.8543",
            "launchAltitude": 70
        }
    + Schema
+ Response 200 (application/json)
Successful request.
+ Response 400 (application/json)
Failed to include needed flight information or headers.
### Remove a flight [DELETE]
+ Headers
    Authentication: (JWT Token)
+ Request (application/json)
    + Body
        {
            "id": 1
        }
    + Schema
+ Response 200 (application/json)
Successful delete.
+ Response 400 (application/json)
Failed to include needed ID or headers.
##  Telemetry [/flight/{callsign}-{flightNumber}/telemetry]
### Get latest telemetry for a flight [GET]
+ Parameters
    + callsign: gomake (required) - Unique identifier for organization or group doing the launches
    + flightNumber: 1 (required) - Unique identifier for flight under a particular callsign
+ Headers
    Authentication: (JWT Token)
+ Request (application/json)
+ Response 200 (application/json)
    + Body
    {
        "content": {
            "imei": 300234063771850,
            "transmitTime": 2016-08-20T16:50:00Z UTC,
            "latitude": 42.3347161667,
            "longitude": -72.6807305,
            "satellites": 10,
            "fixQuality": 2,
            "altitude": 77,
            "sensors": {
                "Temperature": -40.02,
                "Barometer": 338.73,
                "Sound": 247
            }
        },
        "_links": {
            "self": { "href": "/flight/gomake-1/telemetry" },
            "tracker": { "href": "/flight/gomake-1/tracker" }
        }
    }
### Push new telemetry for a flight [POST]
+ Parameters
    + callsign: gomake (required) - Unique identifier for organization or group doing the launches
    + flightNumber: 1 (required) - Unique identifier for flight under a particular callsign
+ Headers
    Authentication: (JWT Token)
+ Request (application/json)
    + Body
    {
        "imei": 300234063771850,
        "transmitTime": 2016-08-20T16:50:00Z UTC,
        "latitude": 42.3347161667,
        "longitude": -72.6807305,
        "satellites": 10,
        "fixQuality": 2,
        "altitude": 77,
        "sensors": {
            "Temperature": -40.02,
            "Barometer": 338.73,
            "Sound": 247
        }
    }
+ Response 200 (application/json)

## History [/flight/{callsign}-{flightNumber}/history]
### Get telemetry logs for a flight [GET]
+ Parameters
    + callsign: gomake (required) - Unique identifier for organization or group doing the launches
    + flightNumber: 1 (required) - Unique identifier for flight under a particular callsign
+ Headers
    Authentication: (JWT Token)
+ Request
    + Body
    {
        "pageLimit": 50,
        "pageOffset": 0,
        "filters": {
            "startDate": 2016-08-20T16:50:00Z UTC,
            "endDate": 2016-08-20T20:50:00Z UTC
        }
    }
+ Response
    + Body
    {
        "content": {
            "totalCount": 1068,
            "pageLimit": 50,
            "pageOffset": 0,
            "filters": {
                "startDate": 2016-08-20T16:50:00Z UTC,
                "endDate": 2016-08-20T20:50:00Z UTC
            },
            "results": [
                {
                    "imei": 300234063771850,
                    "transmitTime": 2016-08-20T16:50:00Z UTC,
                    "latitude": 42.3347161667,
                    "longitude": -72.6807305,
                    "satellites": 10,
                    "fixQuality": 2,
                    "altitude": 77,
                    "sensors": {
                        "Temperature": -40.02,
                        "Barometer": 338.73,
                        "Sound": 247
                    }
                }
            ]        
        }
        "_links": {
            "self": { "href": "/flight/gomake-1/history" }
        }
    }
## Trackers [/flight/{callsign}-{flightNumber}/tracker]
### Get trackers registered for flight [GET]
TBD
## Tracker [/flight/{callsign}-{flightNumber}/tracker/{trackerId}]
### Get individual tracker information [GET]
TBD